### ISSUE TITLE
Separation of validation rules

### ISSUE THREAD

**Issue by oanuna** [justeat/f-validate#30]
Currently this module tests various validation cases (e.g. RegExp tests, length tests, value tests) against DOM elements.

An ideal solution would be to separate the validation mechanisms from the DOM elements and allow the mechanisms to be exported individually. This will save space on the final bundle size when imported and tree-shaken by the consumer, while enabling validation to take place within pure JS modules.

**Comment by ashleynolan** [comment]
Agree that this would be worthwhile so that we can build the postcode validation in to f-validate.

Is this piece of work something we can build on as part of the `f-searchbox` work?

Happy for this to be once the component has a v1 so it doesn't hold up getting the component initially built.  Would just be good to get it onto a roadmap somewhere so it doesn't get forgotten about.

**Comment by oanuna** [comment]
👍  Yeah I wouldn't hold up `f-searchbox` for this but should be done in the next few iterations. Will look to put it in the roadmap
